import React, { useContext, useEffect, useState } from "react";
import { DatasContext } from "@/contexts";

import { getPriceTableFipe } from "@/services/priceTableFipe";
import { Card, CardContent, Stack, Typography } from "@mui/material";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ButtonComponent from "@/components/Button";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const TableFipe = () => {
  const router = useRouter();
  const { data } = useContext(DatasContext);

  const [result, setResult] = useState<any>({});

  useEffect(() => {
    void fetchPriceTableFipe();
  }, []);

  const fetchPriceTableFipe = async () => {
    const resultData = await getPriceTableFipe(data);
    setResult(resultData);
  };

  return (
    <>
      <Head>
        <title>Tabela Fipe - Preço</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Card
          sx={{
            width: "100%",
            padding: "16px",
            backgroundColor: "#c2e9e6",
          }}
        >
          <CardContent
            sx={{
              display: "flex",
              flexDirection: "column",
              padding: "16px",
              rowGap: "16px",
            }}
          >
            <Stack>
              <Typography textAlign={"center"} variant="h6" paragraph={true}>
                <strong>
                  Tabela Fipe: {result?.Modelo} {result?.AnoModelo}
                </strong>
              </Typography>
              <Typography
                textAlign={"center"}
                color={"white"}
                sx={{
                  margin: "0 auto",
                  borderRadius: "16px",
                  backgroundColor: "#008080",
                  width: "16%",
                }}
                variant="h6"
              >
                <strong>{result?.Valor}</strong>
              </Typography>
              <br />
              <Typography textAlign={"center"} variant="body2">
                Este é o preço da compra do veículo.
              </Typography>
            </Stack>
          </CardContent>
        </Card>
        <ButtonComponent handleClick={() => router.push("/")}>
          Voltar
        </ButtonComponent>
      </main>
    </>
  );
};

export default TableFipe;
