import React, { useEffect, useContext } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.css";
import { Grid, Typography, Stack } from "@mui/material";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Select from "@/components/Select";
import ButtonComponent from "@/components/Button";
import { toast } from "react-toastify";

import { Brand, getAllBrands } from "@/services/brands";
import { Model, Year, getAllModelsByCode } from "@/services/modelsCar";
import { DatasContext } from "@/contexts";
import { useForm } from "@/hooks";

const inter = Inter({ subsets: ["latin"] });

type InitalState = {
  brands: Brand[];
  models: Model[];
  years: Year[];
  codeBrand: number;
  codeModel: number;
  codeYear: string;
};

const initialState: InitalState = {
  brands: [],
  models: [],
  years: [],
  codeBrand: 0,
  codeModel: 0,
  codeYear: "",
};

export default function Home() {
  const { setState, state } = useForm<InitalState>({
    initialState,
  });

  const enabled = true;

  const { setData } = useContext(DatasContext);
  const router = useRouter();

  useEffect(() => {
    void fetchAllBrands();
  }, []);

  useEffect(() => {
    const fetchAllModelsByCode = async (code: number) => {
      const data = await getAllModelsByCode(code);
      setState("models", data.modelos);
      setState("years", data.anos);
    };

    if (state.codeBrand > 0) void fetchAllModelsByCode(state.codeBrand);
  }, [state.codeBrand]);

  const fetchAllBrands = async () => {
    const data = await getAllBrands();
    setState("brands", data);
  };

  return (
    <>
      <Head>
        <title>Tabela Fipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Grid xs={12} textAlign={"center"}>
          <Typography variant="h5" component="h2">
            <strong>Tabela Fipe</strong>
          </Typography>
          <Typography variant="subtitle1" paragraph={true}>
            <strong>Consulte o valor de um veículo de forma gratuita</strong>
          </Typography>
          <Card
            sx={{
              width: "100%",
              padding: "16px",
            }}
          >
            <CardContent
              sx={{
                display: "flex",
                flexDirection: "column",
                padding: "16px",
                rowGap: "16px",
              }}
            >
              <Stack>
                <Select
                  label="Marca"
                  list={state.brands}
                  field="codeBrand"
                  handleChange={setState}
                />
              </Stack>
              <Stack>
                <Select
                  label="Modelo"
                  field="codeModel"
                  list={state.models}
                  handleChange={setState}
                />
              </Stack>
              <Stack>
                <Select
                  label="Ano"
                  list={state.years}
                  field="codeYear"
                  handleChange={setState}
                />
              </Stack>
              <ButtonComponent
                disable={state.codeBrand > 0 ? !enabled : enabled}
                handleClick={() => {
                  if (!state.codeBrand || !state.codeModel || !state.codeYear) {
                    toast.error("Preencha todos os campos");
                    return;
                  }
                  setData({ ...state });
                  router.push("price-car-table-fipe");
                }}
              >
                Consultar Preço
              </ButtonComponent>
            </CardContent>
          </Card>
        </Grid>
      </main>
    </>
  );
}
